#!/bin/sh

if [ -b /dev/mmcblk0p27 ]; then
   MODEL="DM250"
else
   MODEL="DM200"
fi

case $1 in
  start)
    /sbin/depmod -a
    if [ $MODEL = "DM250" ]; then
        #DM250
        timedatectl set-local-rtc 0
    else
        timedatectl set-local-rtc 1
    fi
    rm /etc/rc3.d/S10firstboot
  ;;
esac

exit 0
