#!/bin/ash
export PATH="/bin:/sbin:/usr/bin"

mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys

echo "####### wait /dev/mmcblk1p2 #######"

echo "####### mount /dev/mmcblk1p2 #######"
mount -t ext4 -o ro /dev/mmcblk1p2 /root

if [ $? = 0 ]; then
    umount /sys
    umount /proc
    exec /sbin/switch_root /root /sbin/init
fi

echo "####### /dev/mmcblk1p2 mount failed! #######"

echo "####### check restore script #######"
mount -t vfat /dev/mmcblk1p1 /tmp/sd

if [ $? = 0 ]; then
    if [ -e /tmp/sd/_sdboot.sh ]; then
        exec /tmp/sd/_sdboot.sh
    fi
    echo "####### restore script not found #######"
    umount /tmp/sd
fi

echo "####### exec init #######"
exec /sbin/orig/init
