#!/bin/ash
export PATH="/bin:/sbin:/usr/bin"

mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys
/sbin/mdev -s

#echo "####### check init script #######"
mount -t vfat /dev/mmcblk1p1 /mnt/sd

if [ $? = 0 ]; then
    if [ -e /mnt/sd/_init.sh ]; then
        cp /mnt/sd/_init.sh /tmp/_init.sh
        rm /mnt/sd/_init.sh
        umount /mnt/sd
        exec /tmp/_init.sh
    else
        umount /mnt/sd
    fi
fi
#echo "####### init script not found #######"

#echo "####### mount /dev/mmcblk1p2 #######"
mount -t ext4 -o ro /dev/mmcblk1p2 /root

if [ $? = 0 ]; then
    umount /sys
    umount /proc
    exec /sbin/switch_root /root /sbin/init
fi
echo "####### /dev/mmcblk1p2 mount failed! #######"

exec /sbin/orig/init
